module.exports = {
  async up(queryInterface, Sequelize) {
    const now = new Date();
    await queryInterface.bulkInsert('tournament_matches', [
    {
      tournament_id: 1, 
      category_id: 1,
      bracket_id: 1, 
      round: 'quarterfinal',
      match_number: 1,
      player1_id: 2, 
      player2_id: 4, 
      player1_partner_id: 3, 
      player2_partner_id: null,
      scheduled_date: '2024-03-22',
      scheduled_time: '10:00:00',
      actual_start_time: new Date('2024-03-22T10:00:00Z'),
      actual_end_time: new Date('2024-03-22T10:45:00Z'),
      court_id: 1, 
      status: 'completed',
      winner_id: 2, 
      loser_id: 4, 
      score: JSON.stringify({
        set1: { team1: 11, team2: 6 },
        set2: { team1: 11, team2: 8 },
        duration_minutes: 45
      }),
      referee_id: 5, 
      notes: 'Excelente partido, muy competitivo en el primer set',
      created_at: now,
      updated_at: now
    },
    {
      tournament_id: 1, 
      category_id: 2,
      bracket_id: 2, 
      round: 'quarterfinal',
      match_number: 2,
      player1_id: 4, 
      player2_id: 2, 
      player1_partner_id: null, 
      player2_partner_id: null,
      scheduled_date: '2024-03-22',
      scheduled_time: '14:00:00',
      actual_start_time: new Date('2024-03-22T14:00:00Z'),
      actual_end_time: new Date('2024-03-22T14:38:00Z'),
      court_id: 2, 
      status: 'completed',
      winner_id: 4, 
      loser_id: 2, 
      score: JSON.stringify({
        set1: { team1: 11, team2: 5 },
        set2: { team1: 11, team2: 7 },
        duration_minutes: 38
      }),
      referee_id: 6, 
      notes: 'Roberto mostró un nivel superior, excelentes dejadas',
      created_at: now,
      updated_at: now
    },
    {
      tournament_id: 2, 
      category_id: 4,
      bracket_id: 3, 
      round: 'quarterfinal',
      match_number: 1,
      player1_id: 5, 
      player2_id: 2, 
      player1_partner_id: 6, 
      player2_partner_id: 3, 
      scheduled_date: '2024-04-15',
      scheduled_time: '10:00:00',
      actual_start_time: new Date('2024-04-15T10:00:00Z'),
      actual_end_time: null,
      court_id: 4, 
      status: 'in_progress',
      winner_id: null,
      loser_id: null,
      score: JSON.stringify({
        set1: { team1: 11, team2: 9 },
        set2: { team1: 8, team2: 11 },
        set3: { team1: 6, team2: 4 },
        duration_minutes: null
      }),
      referee_id: 1, 
      notes: 'Partido muy parejo, gran nivel técnico de ambos equipos',
      created_at: now,
      updated_at: now
    },
    {
      tournament_id: 3, 
      category_id: 5,
      bracket_id: 4, 
      round: 'final',
      match_number: 1,
      player1_id: 4, 
      player2_id: 5, 
      player1_partner_id: 2, 
      player2_partner_id: 6, 
      scheduled_date: '2024-06-02',
      scheduled_time: '16:00:00',
      actual_start_time: new Date('2024-06-02T16:00:00Z'),
      actual_end_time: new Date('2024-06-02T18:22:00Z'),
      court_id: 3, 
      status: 'completed',
      winner_id: 4, 
      loser_id: 5, 
      score: JSON.stringify({
        set1: { team1: 15, team2: 13 },
        set2: { team1: 10, team2: 15 },
        set3: { team1: 15, team2: 12 },
        set4: { team1: 15, team2: 10 },
        duration_minutes: 142
      }),
      referee_id: 1, 
      notes: 'Final espectacular, nivel profesional excepcional. Gran exhibición técnica.',
      created_at: now,
      updated_at: now
    },
    {
      tournament_id: 1, 
      category_id: 1,
      bracket_id: 1, 
      round: 'semifinal',
      match_number: 1,
      player1_id: 2, 
      player2_id: 3, 
      player1_partner_id: 3, 
      player2_partner_id: 4, 
      scheduled_date: '2024-03-23',
      scheduled_time: '11:00:00',
      actual_start_time: null,
      actual_end_time: null,
      court_id: 1, 
      status: 'scheduled',
      winner_id: null,
      loser_id: null,
      score: null,
      referee_id: 6, 
      notes: 'Semifinal de la categoría principiantes',
      created_at: now,
      updated_at: now
    }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('tournament_matches', {}, {});
  }
};